version: '3.8'
services:
  sql-database-pediatrie-dev:
    image: mysql:8.0
    container_name: dev-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pediatrie_1
    volumes:
      - ./data:/var/lib/mysql
